blogs/urls.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.urls import path
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'articles_app'


urlpatterns = [
    path('', views.ArticleListView.as_view(), name='article_list'),
    path('search/', views.SearchResultsView.as_view(), name='search_results'),
    path('kyrgyzstan/', views.KyrgyzstanArticleListView.as_view(), name='kg_article_list'),
    path('world/', views.WorldArticleListView.as_view(), name='world_article_list'),
    path('sport/', views.SportArticleListView.as_view(), name='sport_article_list'),
    path('create/', views.ArticleCreateView.as_view(), name='article_create'),
    path('<int:pk>/edit/', views.ArticleUpdateView.as_view(), name='article_edit'),
    path('<int:pk>/delete/', views.ArticleDeleteView.as_view(), name='article_delete'),
    path('<int:pk>/', views.ArticleDetailView.as_view(), name='article_detail'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    path('', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

users/urls.py
from django.urls import path
from users.views import (
    UserRegistrationView, IndexPageView,
    CabinetView)

app_name = "users"

urlpatterns = [
    path('accounts/register/', UserRegistrationView.as_view(), name="register"),
    path('accounts/cabinet/', CabinetView.as_view(), name='profile'),
    path('', IndexPageView.as_view(), name='index'),

]

blogs/models.py
from django.db import models
import os
import random
from django.db import models
from django.db.models import Count
from django.conf import settings
from django.utils import timezone

def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance, filename):
    print(instance)
    print(filename)
    new_filename= random.randint(1, 9999999999)
    name, ext = get_filename_ext(filename)
    print(name, ext)
    final_converted_name = "{new_filename}{ext}".format(
        new_filename=new_filename, ext=ext
    )
    print("final function")
    print(final_converted_name)
    print("articles/{new_filename}/{final_converted_name}".format(
        new_filename=new_filename, final_converted_name=final_converted_name
    ))
    return "articles/{new_filename}/{final_converted_name}".format(
        new_filename=new_filename, final_converted_name=final_converted_name
    )

class CustomArticleQuerySet(models.query.QuerySet):
    def get_new(self):
        return self.filter(new=True).order_by('id')[:6]


class ArticlesManager(models.Manager):
    def get_queryset(self):
        return CustomArticleQuerySet(self.model, using=self._db)

    def get_new(self):
        return self.get_queryset().get_new()

class Articles(models.Model):
    title = models.CharField(max_length=120)
    content  = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    KG = 'KG'
    WORLD = 'WORLD'
    SPORT = 'SPORT'
    CATEGORY_OF_ARTICLES = (
        (KG, 'KG'),
        (WORLD, 'WORLD'),
        (SPORT, 'SPORT'),
    )
    article_category = models.CharField(
        max_length=15,
        choices=CATEGORY_OF_ARTICLES,
        default=KG, 
        null=True, 
        blank=True
        )

    objects = ArticlesManager()
    image = models.ImageField(
        upload_to=upload_image_path, 
        null=True, 
        blank=True
    )

    def __str__(self):
        return f"{self.title} -> {self.article_category}"
    
    class Meta:
        ordering = ['-created_date']

blogs/forms.py
from django import forms
from .models import Articles


class ArticleForm(forms.ModelForm):
    
    class Meta:
        model = Articles
        fields = '__all__'

blogs/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import redirect
from django.utils import timezone
from .models import Articles
from .forms import ArticleForm
from .utils import CategoryListViewMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import (
                                ListView, CreateView, 
                                DetailView, UpdateView, 
                                DeleteView
                                )
"""
Вывод результатов поиска 
при помощи filter, models.Q
"""
class SearchResultsView(ListView):
    model = Articles
    template_name = 'blogs/search_results.html' 
    context_object_name = 'articles'

    def get_queryset(self):
        query = self.request.GET.get('search', '')
        if query:
            object_list = self.model.objects.filter(Q(title__icontains=query) | Q(content__icontains=query))
        else:
            object_list = self.model.objects.none()
        return object_list

"""
Вывод списка статей, 
где мы наследуемся от  ListView
"""
class ArticleListView(ListView):
    model = Articles
    template_name = 'blogs/article_list.html'
    context_object_name = 'articles'
    paginate_by = 3
    queryset = Articles.objects.all()


# class ArticleListView(ListView):
#     model = Articles
#     template_name = 'blogs/article_list.html'
#     context_object_name = 'articles'


# class KyrgyzstanArticleListView(CategoryListViewMixin):
#     model = Articles
#     template_name = 'blogs/article_list.html'
#     context_object_name = 'articles'
#     category_a = 'KG'

# class WorldArticleListView(CategoryListViewMixin):   
#     model = Articles
#     template_name = 'blogs/article_list.html'
#     context_object_name = 'articles'
#     category_a = 'WORLD'

# class SportArticleListView(CategoryListViewMixin):   
#     model = Articles
#     template_name = 'blogs/article_list.html'
#     context_object_name = 'articles'
#     category_a = 'SPORT'

"""
Вывод списка статей, 
где категория равняется "KG"
"""
class KyrgyzstanArticleListView(ListView):
    model = Articles
    template_name = 'blogs/article_list.html'
    context_object_name = 'articles'

    def get_queryset(self):
        objects_list = Articles.objects.filter(article_category='KG')
        return objects_list


"""
Вывод списка статей, 
где категория равняется "WORLD"
"""
class WorldArticleListView(ListView):
    model = Articles
    template_name = 'blogs/article_list.html'
    context_object_name = 'articles'

    def get_queryset(self):
        objects_list = Articles.objects.filter(article_category='WORLD')
        return objects_list


"""
Вывод списка статей, 
где категория равняется "SPORT"
"""
class SportArticleListView(ListView):
    model = Articles
    template_name = 'blogs/article_list.html'
    context_object_name = 'articles'

    def get_queryset(self):
        objects_list = Articles.objects.filter(article_category='SPORT')
        return objects_list

"""
Детальное рассмотрение статьи,
где мы наследуемся от DeleteView
"""

class ArticleDetailView(DeleteView):
    model = Articles
    template_name = 'blogs/article_detail.html'
    context_object_name = 'article'

"""
Создание статьи,
где мы наследуемся от CreateView
"""
class ArticleCreateView(CreateView):
    model = Articles
    template_name = 'blogs/article_create.html'
    fields = '__all__'
    success_url = reverse_lazy('articles_app:article_list')

"""
Обновление статьи, 
где мы наследуемся от UpdateView 
"""
class ArticleUpdateView(UpdateView):
    model = Articles
    template_name = 'blogs/article_update.html'
    fields = '__all__'
    
    def get_success_url(self):
        return reverse_lazy(
            'articles_app:article_detail',
            kwargs={'pk': self.object.pk},
        )

"""
Удаление статьи, 
где мы наследуемся от DeleteView 
"""
class ArticleDeleteView(DeleteView):
    model = Articles
    template_name = 'blogs/article_delete.html'
    success_url = reverse_lazy('articles_app:article_list')

templates/blogs/article_create.html
{% extends "base.html" %}
{% load static %}
{% block title%}
    Создать статью
{% endblock %}

    {% block content %}
    {% if user.is_authenticated %}
        <div class="container">
        <form action="{% url 'articles_app:article_create' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit"> Create Article</button>
        </form>
        </div>
    {% endif %}
    {% endblock content %}

templates/blogs/article_delete.html
{% extends "base.html" %}
{% load static %}
{% block title%}
    Удалить статью
{% endblock %}
{% block content %}
{% if user.is_authenticated %}
        <div class="container">
            <h3>Вы уверены, что хотите удалить данную статью?</h3>
            <h6>(статья будет удалена)</h6>
            <button type="submit"><a href="{% url 'articles_app:article_detail'  pk=object.pk%}">Назад</a></button>
        
        <h1><p></p></h1>
        <h1><p></p></h1>
        <h1><p></p></h1>
        
        <form action="{% url 'articles_app:article_delete' pk=object.pk %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <h3><b>"{{ object.title|title }}"</b></h3> 
                <h3><b>{{ object.content }}</b></h3>
                <button type="submit"> Всё равно удалить!</button>
        </form>
        </div>
{% endif %}
{% endblock content %}


   
    
    <button type="submit" name="button" class="btn btn-danger">Delete</button>

templates/blogs/article_detail.html
{% extends "base.html" %}
{% load static %}
{% block title%}
    {{object.title}}
{% endblock %}

{% block content %}

<div class="container">
    <ul>
        <h3>{{ object.title }}</h3>
        <h1><li> Дата создания: {{ object.created_date }}</li></h1>
        <h1><li>Категория: {{ object.article_category }}</li></h1>

        {% if object.image %}
                <img width="600" src="{{ object.image.url }}" alt="">
        {% endif %}

        <div class="container"><h4>{{ object.content }}</h4></div>
        {% if user.is_authenticated %}
        <a href="{% url 'articles_app:article_delete' pk=object.pk %}">
            <button type="button" class="btn btn-danger">УДАЛИТЬ</button>
        </a>



        <a href="{% url 'articles_app:article_edit' pk=object.pk %}">
            <button type="button" class="btn btn-primary">ИЗМЕНИТЬ</button>
        </a>
        {% endif %}

    </ul>
</div>

{% endblock content %}

templates/blogs/article_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	
	<!-- Banner -->
	<section id="banner">
		<div class="content">
			<h2>ПРИВЕТСТВУЮ</h2>
			<p>cвежие и надежные новости</p>
			<a href="#main" class="button scrolly">Поехали !!!</a>
		</div>
	</section>
	<h1>hello world</h1>  
	
    			<!-- Main -->
				<section id="main">
					<div class="container">
						<div class="row gtr-200">
							<div class="col-12">
									<section class="box blog">
										<h2 class="major"><span>Последние новости</span></h2>
										<div>
											<div class="row"> 
												<div class="col-9 col-12-medium">
													{% for article in articles %}
													<div class="content">
														<!-- Featured Post -->
															<article class="box post">
																<header>
																	<h3><a href="{% url 'articles_app:article_detail' pk=article.pk%}">
																		{{ article.title}}

																	</a></h3>
																	<p></p>
																	<ul class="meta">
																		<li class="icon fa-clock">{{ article.created_date }}</li>
																	</ul>
																	<h4>{{ article.article_category }}</h4>
																</header>
																<a href="#" class="image featured"><img src="images/pic05.jpg" alt="" /></a>
																<p>
																	{{ article.content|truncatewords:30 }}
																</p>
																{% if article.image %}
            															<img width="600" src="{{ article.image.url }}" alt="">
																{% endif %}

																<p><a href="{% url 'articles_app:article_detail' pk=article.pk%}" class="button">Читать...</a></p>
															</article>
													</div>
													{% endfor %}
												</div>
												<div class="col-3 col-12-medium">
													<div class="sidebar">

														<!-- Archives -->
												
															{% if user.is_authenticated %}
															<ul class="divided">
																<article class="box post-summary">
																<header id="header">
																		<div>
																			<a href="{% url 'users:profile' %}" class="button">Перейти к профилю</a>
																		</div>
																</header>
																</article>
																<article class="box post-summary">
																<header id="header">
																		<div>
																			<a href="{% url 'password_reset' %}" class="button">Поменять пароль</a>
																		</div>
																</header>
																</article>	
																<article class="box post-summary">
																<header id="header">
																		<div>
																			<a href="{% url 'articles_app:article_create' %}" class="button">Создать статью</a>
																		</div>
																</header>
																</article>
															</ul>
															{% endif %}
														</div>
													</div>
												</div>
										</div>
									</section>

							</div>
						</div>
					</div>
				</section>
				<div class="container mt-5">
					<div class="row">
						<div class="col-6 offset-md-2">
							{% if is_paginated %}
							<nav aria-label="Page navigation example">
								<ul class="pagination">
								{% if page_obj.has_previous %}
									<li class="page-item" ><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
								{% else %}
									<li class="page-item"><span>&laquo;</span></li>
								{% endif %}

								{% for i in paginator.page_range %}
									{% if page_obj.number == i %}
									<li class="page-item active" aria-current="page">
										<span>{{ i }} <span class="sr-only">(current)</span></span>
									</li>
									{% else %}
									<li class="page-item"><a href="?page={{ i }}">{{ i }}</a></li>
									{% endif %}
								{% endfor %}

								{% if page_obj.has_next %}
									<li class="page-item"><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
								{% else %}
									<li class="disabled"><span>&raquo;</span></li>
								{% endif %}
								</ul>
							</nav>
							{% endif %}
						</div>
					</div>	
				</div>	
{% endblock content %}

templates/blogs/article_update.html
{% extends "base.html" %}
{% load static %}
{% block title%}
    Изменить
{% endblock %}
{% block content %}
{% if user.is_authenticated %}
    <div class="container">
    <form action="{% url 'articles_app:article_edit' pk=object.pk %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit"> ОБНОВИТЬ СТАТЬЮ </button>
    </form>
    </div>
{% endif %}
{% endblock content %}

templates/blogs/search_results.html
{% extends "base.html" %}
{% block title%}
    Поиск
{% endblock %}
     {% block content %}
        <div class="container">
        <form action="{% url 'articles_app:search_results'%}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <ul>
                {% for article in articles %}
                <div class="content">
                    <!-- Featured Post -->
                        <article class="box post">
                            <header>
                                <h3><a href="{% url 'articles_app:article_detail' pk=article.pk%}">
                                    {{ article.title}}
                                </a></h3>
                                <p></p>
                                <ul class="meta">
                                    <li class="icon fa-clock">{{ article.created_date }}</li>
                                    <!-- <li class="icon fa-comments"><a href="#">8</a></li> -->
                                </ul>
                                
                            </header>
                            <a href="#" class="image featured"><img src="images/pic05.jpg" alt="" /></a>
                            <p>
                                {{ article.content|truncatewords:30 }}
                            </p>
                            
                            {% if article.image %}
                                    <img width="600" src="{{ article.image.url }}" alt="">
                            {% endif %}

                            <p><a href="{% url 'articles_app:article_detail' pk=article.pk%}" class="button">Читать...</a></p>
                        </article>
                    

                </div>
                {% endfor %}
            </ul>
        </form>
        </div>

    {% endblock content %}